### ISSUE TITLE
Support full-domain wildcard

### ISSUE THREAD

**Issue by nsarno** [dnsimple/exdns#1]
We have a case where we want to give the same answer regardless of what domain is queried. I don't think there's a way to do this at the moment (at least I couldn't find one).

The zone configuration file might look something like this:

```JSON
"name": "*",
"records": [
  {
    "name": "*",
    "type": "SOA",
    ...
  },
  {
    "name": "*",
    "type": "A",
    "data": {
      "ip": "1.2.3.4"
    }
  }
]
```

It's a bit of an edge-case but I'd be happy to submit a PR for it. Let me know what you guys think!

Cheers! :)

**Comment by aeden** [comment]
You are welcome to submit a patch if you would like. I'm trying to decide where the best point is to introduce logic like this, but I'm not certain yet, so I'm interested in seeing what you propose.

**Comment by nsarno** [comment]
I submitted a PR for this, let me know what you think! 🙂

**Comment by aeden** [comment]
Closed by https://github.com/dnsimple/exdns/issues/2
